INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home & Kitchen', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sports & Outdoors', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Beauty & Personal Care', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Toys & Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Clothing, Shoes & Jewelry', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Health & Household', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tools & Home Improvement', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Industrial & Scientific', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Movies & TV', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Music', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Video Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Garden & Outdoor', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Office Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Arts, Crafts & Sewing', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Software', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Digital Downloads', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Collectibles & Fine Art', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Handmade Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Smart Home', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Groceries', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Travel Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Fitness Equipment', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Photography', NOW());